FROM balenalib/aarch64-debian-python:3.7.5-buster-build-20191122

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD [ "python", "./supervisor.py" ]